name: CI

on:
    push:
        branches:
            - main
            - lskatz-qsub-array
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                SRR: [SRR8034137]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: install pixi and update BMGAP environment
              run: |
                curl -fsSL https://pixi.sh/install.sh | sh
                echo "$HOME/.pixi/bin" >> $GITHUB_PATH
                echo "$HOME/BMGAP2/analysis_scripts" >> $GITHUB_PATH
            - name: cache-pixi-env
              id: cache-pixi-env
              uses: actions/cache@v4
              with:
                path: $GITHUB_WORKSPACE/.pixi/envs/default
                key: ${{ runner.os }}-pixi-${{ hashFiles('BMGAP_Conda_all.yml') }}-${{ matrix.SRR }}
            
            - name: Set up pixi env
              if: steps.cache-pixi-env.outputs.cache-hit != 'true'
              run: |
                  pixi init --import BMGAP_Conda_all.yml
                  pixi add awscli sra-tools
                  pixi install
            
            - name: download test data
              run: |
                  mkdir -p test.in
                  pixi run fasterq-dump ${{ matrix.SRR }} --threads 1 --outdir test.in --split-files --skip-technical
                  gzip -v test.in/*.fastq
                  mv -v test.in/${{ matrix.SRR }}_1.fastq.gz test.in/${{ matrix.SRR }}_R1.fastq.gz
                  mv -v test.in/${{ matrix.SRR }}_2.fastq.gz test.in/${{ matrix.SRR }}_R2.fastq.gz
            
            - name: cache-human-genome
              id: cache-human-genome
              uses: actions/cache@v4
              with:
                path: $GITHUB_WORKSPACE/analysis_scripts/hg38
                key: ${{ runner.os }}-hg38-${{ hashFiles('BMGAP_Conda_all.yml') }}-${{ matrix.SRR }}
            
            - name: download human genome
              if: steps.cache-human-genome.outputs.cache-hit != 'true'
              run: |
                  aws s3 --no-sign-request --region eu-west-1 sync s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Sequence/Bowtie2Index/ $HOME/BMGAP2/analysis_scripts/hg38
            - name: view environment
              run: |
                ls -lh $HOME
                echo
                ls -lh test.in
                echo
                ls -lhSR $HOME/BMGAP2
            - name: Run tests
              run: |
                Alignment.sh test.in/${{ matrix.SRR }}_R1.fastq.gz test.in/${{ matrix.SRR }}_R2.fastq.gz test.out "$SRR"
                ls -lhR test.out
