name: CI

on:
    push:
        branches:
            - main
            - lskatz-qsub-array
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                SRR: [SRR8034137]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: install pixi and update BMGAP environment
              run: |
                curl -fsSL https://pixi.sh/install.sh | sh
                echo "$HOME/.pixi/bin" >> $GITHUB_PATH
                echo "$HOME/BMGAP2/analysis_scripts" >> $GITHUB_PATH
            - name: cache-pixi-env
              id: cache-pixi-env
              uses: actions/cache@v4
              with:
                path: $HOME/.pixi/envs
                key: ${{ runner.os }}-pixi-${{ hashFiles('BMGAP_Conda_all.yml') }}-${{ matrix.SRR }}
