name: CI

on:
    push:
        branches:
            - main
            - lskatz-qsub-array
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: install pixi
              run: |
                curl -fsSL https://pixi.sh/install.sh | sh
                echo "$HOME/.pixi/bin" >> $GITHUB_PATH
            - name: Set up pixi env
              run: |
                  pixi init --import BMGAP_Conda_all.yml
                  pixi add awscli sra-tools
                  pixi install
            
            - name: download test data
              run: |
                  mkdir -p test.in
                  for SRR in SRR8034137; do \
                    pixi run fasterq-dump $SRR --threads 1 --outdir test.in --split-files --skip-technical && \
                    gzip -v test.in/*.fastq && \
                    mv -v test.in/${SRR}_1.fastq.gz test.in/${SRR}_R1.fastq.gz && \
                    mv -v test.in/${SRR}_2.fastq.gz test.in/${SRR}_R2.fastq.gz
                  done
                  ls -lh test.in
                  #aws s3 --no-sign-request --region eu-west-1 sync s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Sequence/Bowtie2Index/ ./analysis_scripts/hg38
                  ls -lh test.in

                    
            #- name: Run tests
           #  run: |
                