name: CI

on:
    push:
        branches:
            - main
            - lskatz-qsub-array
    pull_request:
        branches:
            - main

env:
    # increment this number if you want to rebuild the cache
    cache-build-number: 2
    cache-pixi-path: ${{ github.workspace }}/.pixi

jobs:
    build:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                SRR: [SRR8034137]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: install pixi and update BMGAP environment
              run: |
                curl -fsSL https://pixi.sh/install.sh | sh
                echo "$HOME/.pixi/bin" >> $GITHUB_PATH
                echo "$GITHUB_WORKSPACE/analysis_scripts" >> $GITHUB_PATH
                sudo apt-get install -y tree
            - name: cache-pixi-env
              id: cache-pixi-env
              uses: actions/cache@v4
              with:
                path: |
                  $GITHUB_WORKSPACE/.pixi
                  ${{ env.cache-pixi-path }}
                key: ${{ runner.os }}-pixi-${{ hashFiles('BMGAP_Conda_all.yml') }}-${{ env.cache-build-number }}
            
            - name: Set up pixi env
              if: steps.cache-pixi-env.outputs.cache-hit != 'true'
              run: |
                  pixi init --import BMGAP_Conda_all.yml
                  pixi add awscli sra-tools
                  pixi --verbose --verbose install
                  ls -lhSA ${{ env.cache-pixi-path }}
